db: 
  name: "qdrant"
  params:
    collection_name: "test"

chunker:
  name: "chonkie"
  mode: "semantic"
  params: 
    chunk_size: 500
    chunk_overlap: 50
  
embedder:
  name: "hf-dense"
  params:
    model_name: "intfloat/multilingual-e5-small"
    dim: 316
